### ISSUE TITLE
Should this package provide autocomplete suggestions

### ISSUE THREAD

**Issue by chrispahm** [chrispahm/gams-ide#6]
linter-gams for Atom had a GAMS autocomplete package that added model aware autocomplete suggestions
https://github.com/chrispahm/autocomplete-gams/tree/master/data

Is this desired for VSCode as well?

**Comment by kuhnt** [comment]
In general, I think this would be helfpulf. However, when using VScode and gams, there are already suggestions for autocomplete available (via IntelliSense?). I guess what is missing that when typing a parameter or variable, the correspondig sets are provided...

**Comment by chrispahm** [comment]
Implemented in #16, new VSIX is available here https://github.com/chrispahm/gams-ide/files/12861639/gams-ide-0.0.6.vsix.zip

**Comment by chrispahm** [comment]
v0.0.6 also adds a list of all subsets to the sidebar panel
<img width="281" alt="image" src="https://github.com/chrispahm/gams-ide/assets/20703207/3a02026c-a480-47fc-8084-5b873d7f1c2b">

**Comment by chrispahm** [comment]
Will close this now, as autocomplete is now supported. Please open a new issue in case of issues related to the autocomplete function
